[package]
name = "xtask"
edition = "2021"
publish = false
version = "0.12.0"

[dependencies]
# This dependency should stay in line with your router version

apollo-router-scaffold = { git="https://github.com/apollographql/router.git", tag="v1.0.0-alpha.2"}
anyhow = "=1.0.64"
clap = "3.2.10"
